vars:
  - method:
      project: guidance-journal-2023
      project_folder: "../../../../../../../Documents/publications/multi-mpc-2023/results"

stages:
  run:
    foreach:
      unstructured:
        file: random_social/12_corridor.xml
        name: interactive_random_social-12_corridor
      medium:
        file: random_social/8_corridor.xml
        name: interactive_random_social-8_corridor
      low:
        file: random_social/4_corridor.xml
        name: interactive_random_social-4_corridor
    do:
      cmd:
        - source ../../devel/setup.zsh && roslaunch frenet_optimal_planner frenet_optimal_planner.launch overwrite_pedestrian_scenario:=true pedestrian_scenario:="${item.file}" project_name:="${method.project_folder}/data"
      deps:
        - src/frenet_optimal_planner_node.cpp
      params:
        - config/path.yaml:
            - global_path.x
            - dvc_trigger
        - ../pedestrian_simulator/config/configuration.yaml:
            - pedestrian_simulator.pedestrians.seed
            - pedestrian_simulator.pedestrians.process_noise
      outs:
        - ../lmpcc/lmpcc_tools/scripts/data/${method.project_folder}/data/${item.name}_frenet-planner.txt 

  evaluate:
    foreach:
      unstructured:
        file: random_social/12_corridor.xml
        name: interactive_random_social-12_corridor
      medium:
        file: random_social/8_corridor.xml
        name: interactive_random_social-8_corridor
      low:
        file: random_social/4_corridor.xml
        name: interactive_random_social-4_corridor
    do:
      cmd: source ~/.zshrc && cd src/lmpcc/lmpcc_tools/scripts && python3 metrics.py ${item.name} frenet-planner && cd ../../../..
      deps:
        - ../lmpcc/lmpcc_tools/scripts/data/${method.project_folder}/data/${item.name}_frenet-planner.txt 
        - ../lmpcc/lmpcc_tools/scripts/metrics.py
      metrics:
        - ../lmpcc/lmpcc_tools/scripts/data/${method.project_folder}/metrics/${item.name}/frenet-planner.json 

  # compare:
  #   foreach:
  #     unstructured:
  #       file: random_social/12_corridor.xml
  #       name: interactive_random_social-12_corridor
  #     medium:
  #       file: random_social/8_corridor.xml
  #       name: interactive_random_social-8_corridor
  #     low:
  #       file: random_social/4_corridor.xml
  #       name: interactive_random_social-4_corridor
  #   do:
  #     cmd: source ~/.zshrc && cd src/lmpcc/lmpcc_tools/scripts && python3 compare.py -o "pedsim_interaction" -l "interactive_random_social-12_corridor" "interactive_random_social-8_corridor" "interactive_random_social-4_corridor"
  #     deps:
  #       - ../lmpcc/lmpcc_tools/scripts/compare.py
  #       - ../lmpcc/lmpcc_tools/scripts/data/${method.project_folder}/metrics/${item.name}/frenet-planner.json 
  #     outs:
  #      - lmpcc_tools/scripts/data/${method.project_folder}/../latex/tables/pedsim_interaction.tex
